site_name: Python Textbook
theme:
  name: material
  logo: assets/images/logo.png

markdown_extensions:
  -md_in_html

plugins:
  - search
  - mkdocs-video:
      is_video: True
      video_autoplay: True
      css_style:
        width: "100%"
  
