site_name: Python Textbook
theme:
  name: material
  logo: assets/images/logo.png

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocs-video:
      is_video: True
      video_autoplay: True
      css_style:
        width: "100%"
  
